### ISSUE TITLE
Identifier "dispatcher_class" is not defined

### ISSUE THREAD

**Issue by EdwardIII** [texthtml/whoops-silex#2]
Hi,

When trying to use this with Silex 2.0 I'm seeing this error:

```
2015/04/09 09:13:24 [error] 968#0: *51 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Identifier "d" is not defined.' in /vagrant/vendor/pimple/pimple/src/Pimple/Container.php:95
Stack trace: 
#0 /vagrant/vendor/texthtml/whoops-silex/src/SilexApplicationHandler.php(30): Pimple\Container->offsetGet('dispatcher_clas...')
#1 /vagrant/vendor/filp/whoops/src/Whoops/Run.php(256): WhoopsSilex\SilexApplicationHandler->handle(Object(InvalidArgumentException))
#2 [internal function]: Whoops\Run->handleException(Object(InvalidArgumentException))
#3 {main}
  thrown in /vagrant/vendor/pimple/pimple/src/Pimple/Container.php on line 95
PHP message: PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Identifier "dispatcher_class" is not defined.' in /vagrant/vendor/pimple/pimple/src/Pimple/Container.php:95
Stack trace: 
#0 /vagrant/vendor/texthtml/whoops-silex/src/SilexApplicationHandler.php(30): Pimple\Container->offsetGet('dispatcher_clas...')
#1 /vagrant/vendor/filp/whoops/src/Whoops/Run.php(256): WhoopsSilex\SilexApplicationHandler->handle(Object(Whoops\Exception\ErrorException))
#2 /vagrant/vendor/filp/whoops/src/Whoops/Run.php(327): Whoops\Run->handleException(Object(Whoops\Exception\ErrorException))
#3 /vagrant/vendor/filp/whoops/src/Whoops/Run.php(357): Whoops\Run->handleError(1, 'Uncaught except...', '/vagrant/vendor...', 95)
#4 [internal function]: Whoops\Run->handleShutdown()
#5 {main}
  thrown in /vagrant/vendor/pimple/pimple/src/Pimple/Container.php on line 95" while reading response header from upstream, client: 10.40.41.1, server: vagrantbox, request: "GET /api/v0/chain/tsh/hotels/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.40.41.42"
```

Here's my lockfile for specific version numbers: https://gist.github.com/EdwardIII/8f6621a7fddf1c2edf17

**Comment by mathroc** [comment]
it was fixed on master but I had forgotten to push a new release, it should be fixed now

**Comment by EdwardIII** [comment]
Thanks, looks good!
